import type { Folder, Product, Source } from "./types";

const today = new Date().toISOString();

export const SEED_SOURCES: Source[] = [
  { id: "src-bluenile", name: "Blue Nile", url: "https://www.bluenile.com/", active: true, dateAdded: today },
  { id: "src-brilliantearth", name: "Brilliant Earth", url: "https://www.brilliantearth.com/", active: true, dateAdded: today },
  { id: "src-plumdiamonds", name: "Plum Diamonds", url: "https://www.plumdiamonds.com/", active: true, dateAdded: today },
  { id: "src-withclarity", name: "With Clarity", url: "https://www.withclarity.com/", active: true, dateAdded: today },
  { id: "src-ritani", name: "Ritani", url: "https://www.ritani.com/", active: true, dateAdded: today },
  { id: "src-aurate", name: "Aurate New York", url: "https://auratenewyork.com/", active: true, dateAdded: today },
  { id: "src-dorsey", name: "Dorsey", url: "https://www.shopdorsey.com/", active: true, dateAdded: today },
  { id: "src-stoneandstrand", name: "Stone and Strand", url: "https://www.stoneandstrand.com/", active: true, dateAdded: today },
  { id: "src-mejuri", name: "Mejuri", url: "https://mejuri.com/world/en/", active: true, dateAdded: today },
  { id: "src-grownbrilliance", name: "Grown Brilliance", url: "https://www.grownbrilliance.com/", active: true, dateAdded: today },
];

export const SEED_FOLDERS: Folder[] = [
  { id: "fld-trends", name: "Trends", color: "#b08d57", order: 0, dateCreated: today },
  { id: "fld-design", name: "Design Inspiration", color: "#ec4899", order: 1, dateCreated: today },
  { id: "fld-gemstone", name: "Gemstone Ideas", color: "#0d9488", order: 2, dateCreated: today },
  { id: "fld-bridal", name: "Bridal Ideas", color: "#d97706", order: 3, dateCreated: today },
  { id: "fld-macys", name: "Macy's", color: "#ef4444", order: 4, dateCreated: today },
  { id: "fld-bloomies", name: "Bloomingdale's", color: "#525252", order: 5, dateCreated: today },
  { id: "fld-bluenile", name: "Blue Nile", color: "#0ea5e9", order: 6, dateCreated: today },
  { id: "fld-rarecarat", name: "Rare Carat", color: "#10b981", order: 7, dateCreated: today },
  { id: "fld-realreal", name: "The RealReal", color: "#7c3aed", order: 8, dateCreated: today },
  { id: "fld-costco", name: "Costco", color: "#f59e0b", order: 9, dateCreated: today },
];

const img = (seed: string) => `https://picsum.photos/seed/${seed}/800/1000`;

export const SEED_PRODUCTS: Product[] = [
  {
    id: "p-001",
    title: "Round Brilliant Solitaire 1.5ct",
    imageUrl: img("snj-001"),
    productUrl: "https://www.bluenile.com/build-your-own-ring",
    retailer: "Blue Nile",
    sourceId: "src-bluenile",
    price: 9450,
    priceDisplay: "$9,450",
    category: "rings",
    metalType: "Platinum",
    caratWeight: "1.50 ct",
    stoneType: "Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-002",
    title: "Pavé Diamond Hoop Earrings",
    imageUrl: img("snj-002"),
    productUrl: "https://www.brilliantearth.com/",
    retailer: "Brilliant Earth",
    sourceId: "src-brilliantearth",
    price: 2895,
    priceDisplay: "$2,895",
    category: "earrings",
    metalType: "18k White Gold",
    caratWeight: "1.00 ct tw",
    stoneType: "Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-003",
    title: "Emerald Cut Tennis Bracelet",
    imageUrl: img("snj-003"),
    productUrl: "https://www.grownbrilliance.com/",
    retailer: "Grown Brilliance",
    sourceId: "src-grownbrilliance",
    price: 4200,
    priceDisplay: "$4,200",
    category: "tennis",
    metalType: "14k Yellow Gold",
    caratWeight: "5.00 ct tw",
    stoneType: "Lab-Grown Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-004",
    title: "Bezel Set Diamond Pendant",
    imageUrl: img("snj-004"),
    productUrl: "https://auratenewyork.com/",
    retailer: "Aurate New York",
    price: 980,
    priceDisplay: "$980",
    category: "pendants",
    metalType: "14k Yellow Gold",
    caratWeight: "0.25 ct",
    stoneType: "Diamond",
    dateDiscovered: today,
    sourceId: "src-aurate",
    status: "new",
  },
  {
    id: "p-005",
    title: "Sapphire Halo Engagement Ring",
    imageUrl: img("snj-005"),
    productUrl: "https://www.withclarity.com/",
    retailer: "With Clarity",
    sourceId: "src-withclarity",
    price: 3850,
    priceDisplay: "$3,850",
    category: "bridal",
    metalType: "18k White Gold",
    caratWeight: "1.20 ct ctr",
    stoneType: "Sapphire",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-006",
    title: "Gold Chain Link Necklace",
    imageUrl: img("snj-006"),
    productUrl: "https://mejuri.com/world/en/",
    retailer: "Mejuri",
    sourceId: "src-mejuri",
    price: 425,
    priceDisplay: "$425",
    category: "necklaces",
    metalType: "14k Yellow Gold",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-007",
    title: "Pearl Drop Earrings",
    imageUrl: img("snj-007"),
    productUrl: "https://www.shopdorsey.com/",
    retailer: "Dorsey",
    sourceId: "src-dorsey",
    priceDisplay: "POA",
    category: "earrings",
    metalType: "Sterling Silver",
    stoneType: "Freshwater Pearl",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-008",
    title: "Three-Stone Oval Diamond Ring",
    imageUrl: img("snj-008"),
    productUrl: "https://www.ritani.com/",
    retailer: "Ritani",
    sourceId: "src-ritani",
    price: 12500,
    priceDisplay: "$12,500",
    category: "bridal",
    metalType: "Platinum",
    caratWeight: "2.10 ct tw",
    stoneType: "Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-009",
    title: "Ruby Eternity Band",
    imageUrl: img("snj-009"),
    productUrl: "https://www.stoneandstrand.com/",
    retailer: "Stone and Strand",
    sourceId: "src-stoneandstrand",
    price: 1875,
    priceDisplay: "$1,875",
    category: "rings",
    metalType: "14k Rose Gold",
    caratWeight: "1.00 ct tw",
    stoneType: "Ruby",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-010",
    title: "Diamond Tennis Necklace 16\"",
    imageUrl: img("snj-010"),
    productUrl: "https://www.bluenile.com/",
    retailer: "Blue Nile",
    sourceId: "src-bluenile",
    price: 18900,
    priceDisplay: "$18,900",
    category: "tennis",
    metalType: "18k White Gold",
    caratWeight: "10.00 ct tw",
    stoneType: "Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-011",
    title: "Vintage Filigree Ring",
    imageUrl: img("snj-011"),
    productUrl: "https://www.brilliantearth.com/",
    retailer: "Brilliant Earth",
    sourceId: "src-brilliantearth",
    price: 2150,
    priceDisplay: "$2,150",
    category: "rings",
    metalType: "14k Rose Gold",
    caratWeight: "0.75 ct",
    stoneType: "Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-012",
    title: "Stacking Band Set",
    imageUrl: img("snj-012"),
    productUrl: "https://mejuri.com/world/en/",
    retailer: "Mejuri",
    sourceId: "src-mejuri",
    price: 320,
    priceDisplay: "$320",
    category: "rings",
    metalType: "14k Yellow Gold",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-013",
    title: "Emerald Drop Pendant",
    imageUrl: img("snj-013"),
    productUrl: "https://www.plumdiamonds.com/",
    retailer: "Plum Diamonds",
    sourceId: "src-plumdiamonds",
    price: 5400,
    priceDisplay: "$5,400",
    category: "pendants",
    metalType: "18k Yellow Gold",
    stoneType: "Emerald",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-014",
    title: "Bold Cuff Bracelet",
    imageUrl: img("snj-014"),
    productUrl: "https://auratenewyork.com/",
    retailer: "Aurate New York",
    sourceId: "src-aurate",
    price: 1240,
    priceDisplay: "$1,240",
    category: "bracelets",
    metalType: "Gold Vermeil",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-015",
    title: "Cushion Cut Halo Engagement",
    imageUrl: img("snj-015"),
    productUrl: "https://www.grownbrilliance.com/",
    retailer: "Grown Brilliance",
    sourceId: "src-grownbrilliance",
    price: 4675,
    priceDisplay: "$4,675",
    category: "bridal",
    metalType: "14k White Gold",
    caratWeight: "1.50 ct ctr",
    stoneType: "Lab-Grown Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-016",
    title: "Diamond Huggies",
    imageUrl: img("snj-016"),
    productUrl: "https://mejuri.com/world/en/",
    retailer: "Mejuri",
    sourceId: "src-mejuri",
    price: 590,
    priceDisplay: "$590",
    category: "earrings",
    metalType: "14k Yellow Gold",
    caratWeight: "0.20 ct tw",
    stoneType: "Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-017",
    title: "Riviera Diamond Necklace",
    imageUrl: img("snj-017"),
    productUrl: "https://www.bluenile.com/",
    retailer: "Blue Nile",
    sourceId: "src-bluenile",
    price: 24500,
    priceDisplay: "$24,500",
    category: "necklaces",
    metalType: "Platinum",
    caratWeight: "15.00 ct tw",
    stoneType: "Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-018",
    title: "Signet Initial Ring",
    imageUrl: img("snj-018"),
    productUrl: "https://www.shopdorsey.com/",
    retailer: "Dorsey",
    sourceId: "src-dorsey",
    price: 285,
    priceDisplay: "$285",
    category: "rings",
    metalType: "Gold-Plated Brass",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-019",
    title: "Aquamarine Cocktail Ring",
    imageUrl: img("snj-019"),
    productUrl: "https://www.stoneandstrand.com/",
    retailer: "Stone and Strand",
    sourceId: "src-stoneandstrand",
    price: 2980,
    priceDisplay: "$2,980",
    category: "gemstone",
    metalType: "14k Yellow Gold",
    stoneType: "Aquamarine",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-020",
    title: "Pavé Tennis Bracelet 7\"",
    imageUrl: img("snj-020"),
    productUrl: "https://www.ritani.com/",
    retailer: "Ritani",
    sourceId: "src-ritani",
    price: 8900,
    priceDisplay: "$8,900",
    category: "tennis",
    metalType: "18k White Gold",
    caratWeight: "7.00 ct tw",
    stoneType: "Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-021",
    title: "Layered Chain Necklace",
    imageUrl: img("snj-021"),
    productUrl: "https://auratenewyork.com/",
    retailer: "Aurate New York",
    sourceId: "src-aurate",
    price: 750,
    priceDisplay: "$750",
    category: "necklaces",
    metalType: "14k Yellow Gold",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-022",
    title: "Pear Shaped Diamond Studs",
    imageUrl: img("snj-022"),
    productUrl: "https://www.withclarity.com/",
    retailer: "With Clarity",
    sourceId: "src-withclarity",
    price: 3290,
    priceDisplay: "$3,290",
    category: "earrings",
    metalType: "Platinum",
    caratWeight: "1.50 ct tw",
    stoneType: "Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-023",
    title: "Sapphire and Diamond Cluster Ring",
    imageUrl: img("snj-023"),
    productUrl: "https://www.plumdiamonds.com/",
    retailer: "Plum Diamonds",
    sourceId: "src-plumdiamonds",
    price: 6150,
    priceDisplay: "$6,150",
    category: "gemstone",
    metalType: "18k White Gold",
    caratWeight: "2.30 ct tw",
    stoneType: "Blue Sapphire",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-024",
    title: "Curved Wedding Band",
    imageUrl: img("snj-024"),
    productUrl: "https://www.brilliantearth.com/",
    retailer: "Brilliant Earth",
    sourceId: "src-brilliantearth",
    price: 1190,
    priceDisplay: "$1,190",
    category: "bridal",
    metalType: "14k Yellow Gold",
    caratWeight: "0.20 ct tw",
    stoneType: "Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-025",
    title: "Bold Gold Hoops",
    imageUrl: img("snj-025"),
    productUrl: "https://www.shopdorsey.com/",
    retailer: "Dorsey",
    sourceId: "src-dorsey",
    price: 195,
    priceDisplay: "$195",
    category: "earrings",
    metalType: "Gold-Plated Brass",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-026",
    title: "Pavé Diamond Cuff",
    imageUrl: img("snj-026"),
    productUrl: "https://www.bluenile.com/",
    retailer: "Blue Nile",
    sourceId: "src-bluenile",
    price: 7400,
    priceDisplay: "$7,400",
    category: "bracelets",
    metalType: "18k White Gold",
    caratWeight: "3.00 ct tw",
    stoneType: "Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-027",
    title: "Opal Pendant on Cable Chain",
    imageUrl: img("snj-027"),
    productUrl: "https://mejuri.com/world/en/",
    retailer: "Mejuri",
    sourceId: "src-mejuri",
    price: 280,
    priceDisplay: "$280",
    category: "pendants",
    metalType: "14k Yellow Gold",
    stoneType: "Opal",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-028",
    title: "Marquise Diamond Eternity",
    imageUrl: img("snj-028"),
    productUrl: "https://www.grownbrilliance.com/",
    retailer: "Grown Brilliance",
    sourceId: "src-grownbrilliance",
    price: 5950,
    priceDisplay: "$5,950",
    category: "rings",
    metalType: "Platinum",
    caratWeight: "3.00 ct tw",
    stoneType: "Lab-Grown Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-029",
    title: "Charm Pendant Necklace",
    imageUrl: img("snj-029"),
    productUrl: "https://www.stoneandstrand.com/",
    retailer: "Stone and Strand",
    sourceId: "src-stoneandstrand",
    price: 660,
    priceDisplay: "$660",
    category: "necklaces",
    metalType: "14k Yellow Gold",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-030",
    title: "Tanzanite Statement Ring",
    imageUrl: img("snj-030"),
    productUrl: "https://www.plumdiamonds.com/",
    retailer: "Plum Diamonds",
    sourceId: "src-plumdiamonds",
    price: 4380,
    priceDisplay: "$4,380",
    category: "gemstone",
    metalType: "18k White Gold",
    stoneType: "Tanzanite",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-031",
    title: "Princess Cut Solitaire",
    imageUrl: img("snj-031"),
    productUrl: "https://www.ritani.com/",
    retailer: "Ritani",
    sourceId: "src-ritani",
    price: 6750,
    priceDisplay: "$6,750",
    category: "bridal",
    metalType: "Platinum",
    caratWeight: "1.00 ct",
    stoneType: "Diamond",
    dateDiscovered: today,
    status: "new",
  },
  {
    id: "p-032",
    title: "Diamond Bar Bracelet",
    imageUrl: img("snj-032"),
    productUrl: "https://auratenewyork.com/",
    retailer: "Aurate New York",
    sourceId: "src-aurate",
    price: 1450,
    priceDisplay: "$1,450",
    category: "bracelets",
    metalType: "14k Yellow Gold",
    caratWeight: "0.30 ct tw",
    stoneType: "Diamond",
    dateDiscovered: today,
    status: "new",
  },
];
